#ifndef EMBEDDED_BINARY_GENERATED_PRIV_H_
#define EMBEDDED_BINARY_GENERATED_PRIV_H_

#ifdef __APPLE__

const char EMBEDDED_BINARY_RESOURCE_NAMES_MACOS[][16] = {
    @RESOURCE_FILE_NAME_MACOS_DEFINES @};

#else

@RESOURCE_FILE_NAME_LINUX_EXTERNS @

    const unsigned char* EMBEDDED_BINARY_RESOURCE_STARTS_LINUX[] = {
        @RESOURCE_FILE_NAME_LINUX_START_DEFINES @};
const unsigned char* EMBEDDED_BINARY_RESOURCE_ENDS_LINUX[] = {
    @RESOURCE_FILE_NAME_LINUX_END_DEFINES @};

#endif

#endif
